### ISSUE TITLE
exampleSite for Hugo Theme Site

### ISSUE THREAD

**Issue by bep** [nilproductions/hugo-incorporated#24]
See my preview build of the Hugo theme site:

http://185.52.0.94:1313/hugo-incorporated/

(the site may go up and down)

Compare that to

http://185.52.0.94:1313/artists/

With most themes I have tried to get it up and running with the generic Hugo Basic Example (https://github.com/spf13/HugoBasicExample). 

But some themes are "too custom", so that isn't possible.

So I added support for a theme having a self-contained exampleSite. In the Artist example above, see:

https://github.com/digitalcraftsman/hugo-artists-theme/tree/master/exampleSite

For Hugo Incorporated I have just disabled the demo for now, but I'm happy to turn it on if we can get it either up and running with the basic example, or probably better, add an exampleSite to this repo.

**Comment by spf13** [comment]
@imperialwicket Can you please look into this so we can add your demo to the theme site.

**Comment by imperialwicket** [comment]
@bep or @spf13 this seems to work in [branch '24'](https://github.com/nilproductions/hugo-incorporated/tree/24), if my assumptions about running the example sites are accurate. Can you confirm and I'll merge this?

**Comment by bep** [comment]
Yes, that looks correct.

**Comment by imperialwicket** [comment]
Thanks!
